version: '3.1'

services:

  mongo:
    container_name: mongodb
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pis12345
      MONGO_INITDB_DATABASE: main
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb

  # mongo-express:
  #   container_name: mongoexpress
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: pis12345
  #     ME_CONFIG_MONGODB_URL: mongodb://root:pis12345@mongo:27017/

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local